apiVersion: apps/v1
kind: Deployment
metadata:
    name: producer-app
    labels:
        app: producer-app
    namespace: stage-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: producer-app
    template:
        metadata:
            labels:
                app: producer-app
            annotations:
                dapr.io/enabled: "true"
                dapr.io/app-id: "producer-app"
                dapr.io/enable-api-logging: "true"
        spec:
            containers:
                - name: producer-app
                  image: localhost:5000/producer-app:latest
                  imagePullPolicy: Always
                  env:
                      - name: PRODUCER_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name