apiVersion: apps/v1
kind: Deployment
metadata:
    name: consumer-app
    labels:
        app: consumer-app
    namespace: stage-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: consumer-app
    template:
        metadata:
            labels:
                app: consumer-app
        spec:
            containers:
                - name: consumer-app
                  image: localhost:5000/consumer-app:latest
                  imagePullPolicy: Always