### log something
POST {{host}}/log
Accept: application/json
Content-Type: application/json

{
  "test-key": "test-value"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}